[build]
builder = "nixpacks"
buildCommand = "yarn build:backend"

[deploy]
startCommand = "yarn start:backend"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
