/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTransactionsRouteImport } from './routes/_auth/transactions'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthHouseholdRouteImport } from './routes/_auth/household'
import { Route as AuthGoalsRouteImport } from './routes/_auth/goals'
import { Route as AuthCategoriesRouteImport } from './routes/_auth/categories'
import { Route as AuthBudgetsRouteImport } from './routes/_auth/budgets'
import { Route as AuthBillsRouteImport } from './routes/_auth/bills'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsRoute = AuthTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHouseholdRoute = AuthHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGoalsRoute = AuthGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriesRoute = AuthCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBudgetsRoute = AuthBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBillsRoute = AuthBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/bills': typeof AuthBillsRoute
  '/budgets': typeof AuthBudgetsRoute
  '/categories': typeof AuthCategoriesRoute
  '/goals': typeof AuthGoalsRoute
  '/household': typeof AuthHouseholdRoute
  '/reports': typeof AuthReportsRoute
  '/settings': typeof AuthSettingsRoute
  '/transactions': typeof AuthTransactionsRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/bills': typeof AuthBillsRoute
  '/budgets': typeof AuthBudgetsRoute
  '/categories': typeof AuthCategoriesRoute
  '/goals': typeof AuthGoalsRoute
  '/household': typeof AuthHouseholdRoute
  '/reports': typeof AuthReportsRoute
  '/settings': typeof AuthSettingsRoute
  '/transactions': typeof AuthTransactionsRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_auth/bills': typeof AuthBillsRoute
  '/_auth/budgets': typeof AuthBudgetsRoute
  '/_auth/categories': typeof AuthCategoriesRoute
  '/_auth/goals': typeof AuthGoalsRoute
  '/_auth/household': typeof AuthHouseholdRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/transactions': typeof AuthTransactionsRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/bills'
    | '/budgets'
    | '/categories'
    | '/goals'
    | '/household'
    | '/reports'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/bills'
    | '/budgets'
    | '/categories'
    | '/goals'
    | '/household'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/_auth/bills'
    | '/_auth/budgets'
    | '/_auth/categories'
    | '/_auth/goals'
    | '/_auth/household'
    | '/_auth/reports'
    | '/_auth/settings'
    | '/_auth/transactions'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/household': {
      id: '/_auth/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthHouseholdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/goals': {
      id: '/_auth/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthGoalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categories': {
      id: '/_auth/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/budgets': {
      id: '/_auth/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthBudgetsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bills': {
      id: '/_auth/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthBillsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthBillsRoute: typeof AuthBillsRoute
  AuthBudgetsRoute: typeof AuthBudgetsRoute
  AuthCategoriesRoute: typeof AuthCategoriesRoute
  AuthGoalsRoute: typeof AuthGoalsRoute
  AuthHouseholdRoute: typeof AuthHouseholdRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthTransactionsRoute: typeof AuthTransactionsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBillsRoute: AuthBillsRoute,
  AuthBudgetsRoute: AuthBudgetsRoute,
  AuthCategoriesRoute: AuthCategoriesRoute,
  AuthGoalsRoute: AuthGoalsRoute,
  AuthHouseholdRoute: AuthHouseholdRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthTransactionsRoute: AuthTransactionsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
